name: Docker Workflow

on: 
  push:
    branches:
      - 'main'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/efrei_devops_tp3:latest

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image to Azure Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20221477:latest
        env:
          OPENWEATHER_API: ${{ secrets.API_OPENWEATHER }}

      - name: Authenticate with Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Container to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          name: 20221477
          resource_group: ${{ secrets.RESOURCE_GROUP }}
          location: 'germanywestcentral'
          dns_name_label: efrei_devops_tp3
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20221477:latest
          registry_login_server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
          secure_environment_variables: OPENWEATHER_API_KEY=${{ secrets.API_OPENWEATHER }}
